/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class examples_Register */

#ifndef _Included_examples_Register
#define _Included_examples_Register
#ifdef __cplusplus
extern "C" {
#endif
#undef examples_Register_FOCUS_TRAVERSABLE_UNKNOWN
#define examples_Register_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef examples_Register_FOCUS_TRAVERSABLE_DEFAULT
#define examples_Register_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef examples_Register_FOCUS_TRAVERSABLE_SET
#define examples_Register_FOCUS_TRAVERSABLE_SET 2L
#undef examples_Register_TOP_ALIGNMENT
#define examples_Register_TOP_ALIGNMENT 0.0f
#undef examples_Register_CENTER_ALIGNMENT
#define examples_Register_CENTER_ALIGNMENT 0.5f
#undef examples_Register_BOTTOM_ALIGNMENT
#define examples_Register_BOTTOM_ALIGNMENT 1.0f
#undef examples_Register_LEFT_ALIGNMENT
#define examples_Register_LEFT_ALIGNMENT 0.0f
#undef examples_Register_RIGHT_ALIGNMENT
#define examples_Register_RIGHT_ALIGNMENT 1.0f
#undef examples_Register_serialVersionUID
#define examples_Register_serialVersionUID -7644114512714619750LL
#undef examples_Register_serialVersionUID
#define examples_Register_serialVersionUID 4613797578919906343LL
#undef examples_Register_INCLUDE_SELF
#define examples_Register_INCLUDE_SELF 1L
#undef examples_Register_SEARCH_HEAVYWEIGHTS
#define examples_Register_SEARCH_HEAVYWEIGHTS 1L
#undef examples_Register_OPENED
#define examples_Register_OPENED 1L
#undef examples_Register_serialVersionUID
#define examples_Register_serialVersionUID 4497834738069338734LL
#undef examples_Register_DEFAULT_CURSOR
#define examples_Register_DEFAULT_CURSOR 0L
#undef examples_Register_CROSSHAIR_CURSOR
#define examples_Register_CROSSHAIR_CURSOR 1L
#undef examples_Register_TEXT_CURSOR
#define examples_Register_TEXT_CURSOR 2L
#undef examples_Register_WAIT_CURSOR
#define examples_Register_WAIT_CURSOR 3L
#undef examples_Register_SW_RESIZE_CURSOR
#define examples_Register_SW_RESIZE_CURSOR 4L
#undef examples_Register_SE_RESIZE_CURSOR
#define examples_Register_SE_RESIZE_CURSOR 5L
#undef examples_Register_NW_RESIZE_CURSOR
#define examples_Register_NW_RESIZE_CURSOR 6L
#undef examples_Register_NE_RESIZE_CURSOR
#define examples_Register_NE_RESIZE_CURSOR 7L
#undef examples_Register_N_RESIZE_CURSOR
#define examples_Register_N_RESIZE_CURSOR 8L
#undef examples_Register_S_RESIZE_CURSOR
#define examples_Register_S_RESIZE_CURSOR 9L
#undef examples_Register_W_RESIZE_CURSOR
#define examples_Register_W_RESIZE_CURSOR 10L
#undef examples_Register_E_RESIZE_CURSOR
#define examples_Register_E_RESIZE_CURSOR 11L
#undef examples_Register_HAND_CURSOR
#define examples_Register_HAND_CURSOR 12L
#undef examples_Register_MOVE_CURSOR
#define examples_Register_MOVE_CURSOR 13L
#undef examples_Register_NORMAL
#define examples_Register_NORMAL 0L
#undef examples_Register_ICONIFIED
#define examples_Register_ICONIFIED 1L
#undef examples_Register_MAXIMIZED_HORIZ
#define examples_Register_MAXIMIZED_HORIZ 2L
#undef examples_Register_MAXIMIZED_VERT
#define examples_Register_MAXIMIZED_VERT 4L
#undef examples_Register_MAXIMIZED_BOTH
#define examples_Register_MAXIMIZED_BOTH 6L
#undef examples_Register_serialVersionUID
#define examples_Register_serialVersionUID 2673458971256075116LL
#undef examples_Register_EXIT_ON_CLOSE
#define examples_Register_EXIT_ON_CLOSE 3L
/*
 * Class:     examples_Register
 * Method:    submitRegister
 * Signature: (ILjava/lang/String;Ljava/lang/String;)C
 */
JNIEXPORT jchar JNICALL Java_examples_Register_submitRegister
  (JNIEnv *, jobject, jint, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
