/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class examples_Talk */

#ifndef _Included_examples_Talk
#define _Included_examples_Talk
#ifdef __cplusplus
extern "C" {
#endif
#undef examples_Talk_FOCUS_TRAVERSABLE_UNKNOWN
#define examples_Talk_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef examples_Talk_FOCUS_TRAVERSABLE_DEFAULT
#define examples_Talk_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef examples_Talk_FOCUS_TRAVERSABLE_SET
#define examples_Talk_FOCUS_TRAVERSABLE_SET 2L
#undef examples_Talk_TOP_ALIGNMENT
#define examples_Talk_TOP_ALIGNMENT 0.0f
#undef examples_Talk_CENTER_ALIGNMENT
#define examples_Talk_CENTER_ALIGNMENT 0.5f
#undef examples_Talk_BOTTOM_ALIGNMENT
#define examples_Talk_BOTTOM_ALIGNMENT 1.0f
#undef examples_Talk_LEFT_ALIGNMENT
#define examples_Talk_LEFT_ALIGNMENT 0.0f
#undef examples_Talk_RIGHT_ALIGNMENT
#define examples_Talk_RIGHT_ALIGNMENT 1.0f
#undef examples_Talk_serialVersionUID
#define examples_Talk_serialVersionUID -7644114512714619750LL
#undef examples_Talk_serialVersionUID
#define examples_Talk_serialVersionUID 4613797578919906343LL
#undef examples_Talk_INCLUDE_SELF
#define examples_Talk_INCLUDE_SELF 1L
#undef examples_Talk_SEARCH_HEAVYWEIGHTS
#define examples_Talk_SEARCH_HEAVYWEIGHTS 1L
#undef examples_Talk_OPENED
#define examples_Talk_OPENED 1L
#undef examples_Talk_serialVersionUID
#define examples_Talk_serialVersionUID 4497834738069338734LL
#undef examples_Talk_DEFAULT_CURSOR
#define examples_Talk_DEFAULT_CURSOR 0L
#undef examples_Talk_CROSSHAIR_CURSOR
#define examples_Talk_CROSSHAIR_CURSOR 1L
#undef examples_Talk_TEXT_CURSOR
#define examples_Talk_TEXT_CURSOR 2L
#undef examples_Talk_WAIT_CURSOR
#define examples_Talk_WAIT_CURSOR 3L
#undef examples_Talk_SW_RESIZE_CURSOR
#define examples_Talk_SW_RESIZE_CURSOR 4L
#undef examples_Talk_SE_RESIZE_CURSOR
#define examples_Talk_SE_RESIZE_CURSOR 5L
#undef examples_Talk_NW_RESIZE_CURSOR
#define examples_Talk_NW_RESIZE_CURSOR 6L
#undef examples_Talk_NE_RESIZE_CURSOR
#define examples_Talk_NE_RESIZE_CURSOR 7L
#undef examples_Talk_N_RESIZE_CURSOR
#define examples_Talk_N_RESIZE_CURSOR 8L
#undef examples_Talk_S_RESIZE_CURSOR
#define examples_Talk_S_RESIZE_CURSOR 9L
#undef examples_Talk_W_RESIZE_CURSOR
#define examples_Talk_W_RESIZE_CURSOR 10L
#undef examples_Talk_E_RESIZE_CURSOR
#define examples_Talk_E_RESIZE_CURSOR 11L
#undef examples_Talk_HAND_CURSOR
#define examples_Talk_HAND_CURSOR 12L
#undef examples_Talk_MOVE_CURSOR
#define examples_Talk_MOVE_CURSOR 13L
#undef examples_Talk_NORMAL
#define examples_Talk_NORMAL 0L
#undef examples_Talk_ICONIFIED
#define examples_Talk_ICONIFIED 1L
#undef examples_Talk_MAXIMIZED_HORIZ
#define examples_Talk_MAXIMIZED_HORIZ 2L
#undef examples_Talk_MAXIMIZED_VERT
#define examples_Talk_MAXIMIZED_VERT 4L
#undef examples_Talk_MAXIMIZED_BOTH
#define examples_Talk_MAXIMIZED_BOTH 6L
#undef examples_Talk_serialVersionUID
#define examples_Talk_serialVersionUID 2673458971256075116LL
#undef examples_Talk_EXIT_ON_CLOSE
#define examples_Talk_EXIT_ON_CLOSE 3L
/*
 * Class:     examples_Talk
 * Method:    sendMsg
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_examples_Talk_sendMsg
  (JNIEnv *, jobject, jint, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
