/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class examples_Chat */

#ifndef _Included_examples_Chat
#define _Included_examples_Chat
#ifdef __cplusplus
extern "C" {
#endif
#undef examples_Chat_FOCUS_TRAVERSABLE_UNKNOWN
#define examples_Chat_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef examples_Chat_FOCUS_TRAVERSABLE_DEFAULT
#define examples_Chat_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef examples_Chat_FOCUS_TRAVERSABLE_SET
#define examples_Chat_FOCUS_TRAVERSABLE_SET 2L
#undef examples_Chat_TOP_ALIGNMENT
#define examples_Chat_TOP_ALIGNMENT 0.0f
#undef examples_Chat_CENTER_ALIGNMENT
#define examples_Chat_CENTER_ALIGNMENT 0.5f
#undef examples_Chat_BOTTOM_ALIGNMENT
#define examples_Chat_BOTTOM_ALIGNMENT 1.0f
#undef examples_Chat_LEFT_ALIGNMENT
#define examples_Chat_LEFT_ALIGNMENT 0.0f
#undef examples_Chat_RIGHT_ALIGNMENT
#define examples_Chat_RIGHT_ALIGNMENT 1.0f
#undef examples_Chat_serialVersionUID
#define examples_Chat_serialVersionUID -7644114512714619750LL
#undef examples_Chat_serialVersionUID
#define examples_Chat_serialVersionUID 4613797578919906343LL
#undef examples_Chat_INCLUDE_SELF
#define examples_Chat_INCLUDE_SELF 1L
#undef examples_Chat_SEARCH_HEAVYWEIGHTS
#define examples_Chat_SEARCH_HEAVYWEIGHTS 1L
#undef examples_Chat_OPENED
#define examples_Chat_OPENED 1L
#undef examples_Chat_serialVersionUID
#define examples_Chat_serialVersionUID 4497834738069338734LL
#undef examples_Chat_DEFAULT_CURSOR
#define examples_Chat_DEFAULT_CURSOR 0L
#undef examples_Chat_CROSSHAIR_CURSOR
#define examples_Chat_CROSSHAIR_CURSOR 1L
#undef examples_Chat_TEXT_CURSOR
#define examples_Chat_TEXT_CURSOR 2L
#undef examples_Chat_WAIT_CURSOR
#define examples_Chat_WAIT_CURSOR 3L
#undef examples_Chat_SW_RESIZE_CURSOR
#define examples_Chat_SW_RESIZE_CURSOR 4L
#undef examples_Chat_SE_RESIZE_CURSOR
#define examples_Chat_SE_RESIZE_CURSOR 5L
#undef examples_Chat_NW_RESIZE_CURSOR
#define examples_Chat_NW_RESIZE_CURSOR 6L
#undef examples_Chat_NE_RESIZE_CURSOR
#define examples_Chat_NE_RESIZE_CURSOR 7L
#undef examples_Chat_N_RESIZE_CURSOR
#define examples_Chat_N_RESIZE_CURSOR 8L
#undef examples_Chat_S_RESIZE_CURSOR
#define examples_Chat_S_RESIZE_CURSOR 9L
#undef examples_Chat_W_RESIZE_CURSOR
#define examples_Chat_W_RESIZE_CURSOR 10L
#undef examples_Chat_E_RESIZE_CURSOR
#define examples_Chat_E_RESIZE_CURSOR 11L
#undef examples_Chat_HAND_CURSOR
#define examples_Chat_HAND_CURSOR 12L
#undef examples_Chat_MOVE_CURSOR
#define examples_Chat_MOVE_CURSOR 13L
#undef examples_Chat_NORMAL
#define examples_Chat_NORMAL 0L
#undef examples_Chat_ICONIFIED
#define examples_Chat_ICONIFIED 1L
#undef examples_Chat_MAXIMIZED_HORIZ
#define examples_Chat_MAXIMIZED_HORIZ 2L
#undef examples_Chat_MAXIMIZED_VERT
#define examples_Chat_MAXIMIZED_VERT 4L
#undef examples_Chat_MAXIMIZED_BOTH
#define examples_Chat_MAXIMIZED_BOTH 6L
#undef examples_Chat_serialVersionUID
#define examples_Chat_serialVersionUID 2673458971256075116LL
#undef examples_Chat_EXIT_ON_CLOSE
#define examples_Chat_EXIT_ON_CLOSE 3L
/*
 * Class:     examples_Chat
 * Method:    listUsr
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_examples_Chat_listUsr
  (JNIEnv *, jobject, jint);

/*
 * Class:     examples_Chat
 * Method:    waitForServer
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_examples_Chat_waitForServer
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class examples_Chat_WaitForServer */

#ifndef _Included_examples_Chat_WaitForServer
#define _Included_examples_Chat_WaitForServer
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
