/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class examples_Antenna */

#ifndef _Included_examples_Antenna
#define _Included_examples_Antenna
#ifdef __cplusplus
extern "C" {
#endif
#undef examples_Antenna_FOCUS_TRAVERSABLE_UNKNOWN
#define examples_Antenna_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef examples_Antenna_FOCUS_TRAVERSABLE_DEFAULT
#define examples_Antenna_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef examples_Antenna_FOCUS_TRAVERSABLE_SET
#define examples_Antenna_FOCUS_TRAVERSABLE_SET 2L
#undef examples_Antenna_TOP_ALIGNMENT
#define examples_Antenna_TOP_ALIGNMENT 0.0f
#undef examples_Antenna_CENTER_ALIGNMENT
#define examples_Antenna_CENTER_ALIGNMENT 0.5f
#undef examples_Antenna_BOTTOM_ALIGNMENT
#define examples_Antenna_BOTTOM_ALIGNMENT 1.0f
#undef examples_Antenna_LEFT_ALIGNMENT
#define examples_Antenna_LEFT_ALIGNMENT 0.0f
#undef examples_Antenna_RIGHT_ALIGNMENT
#define examples_Antenna_RIGHT_ALIGNMENT 1.0f
#undef examples_Antenna_serialVersionUID
#define examples_Antenna_serialVersionUID -7644114512714619750LL
#undef examples_Antenna_serialVersionUID
#define examples_Antenna_serialVersionUID 4613797578919906343LL
#undef examples_Antenna_INCLUDE_SELF
#define examples_Antenna_INCLUDE_SELF 1L
#undef examples_Antenna_SEARCH_HEAVYWEIGHTS
#define examples_Antenna_SEARCH_HEAVYWEIGHTS 1L
#undef examples_Antenna_OPENED
#define examples_Antenna_OPENED 1L
#undef examples_Antenna_serialVersionUID
#define examples_Antenna_serialVersionUID 4497834738069338734LL
#undef examples_Antenna_DEFAULT_CURSOR
#define examples_Antenna_DEFAULT_CURSOR 0L
#undef examples_Antenna_CROSSHAIR_CURSOR
#define examples_Antenna_CROSSHAIR_CURSOR 1L
#undef examples_Antenna_TEXT_CURSOR
#define examples_Antenna_TEXT_CURSOR 2L
#undef examples_Antenna_WAIT_CURSOR
#define examples_Antenna_WAIT_CURSOR 3L
#undef examples_Antenna_SW_RESIZE_CURSOR
#define examples_Antenna_SW_RESIZE_CURSOR 4L
#undef examples_Antenna_SE_RESIZE_CURSOR
#define examples_Antenna_SE_RESIZE_CURSOR 5L
#undef examples_Antenna_NW_RESIZE_CURSOR
#define examples_Antenna_NW_RESIZE_CURSOR 6L
#undef examples_Antenna_NE_RESIZE_CURSOR
#define examples_Antenna_NE_RESIZE_CURSOR 7L
#undef examples_Antenna_N_RESIZE_CURSOR
#define examples_Antenna_N_RESIZE_CURSOR 8L
#undef examples_Antenna_S_RESIZE_CURSOR
#define examples_Antenna_S_RESIZE_CURSOR 9L
#undef examples_Antenna_W_RESIZE_CURSOR
#define examples_Antenna_W_RESIZE_CURSOR 10L
#undef examples_Antenna_E_RESIZE_CURSOR
#define examples_Antenna_E_RESIZE_CURSOR 11L
#undef examples_Antenna_HAND_CURSOR
#define examples_Antenna_HAND_CURSOR 12L
#undef examples_Antenna_MOVE_CURSOR
#define examples_Antenna_MOVE_CURSOR 13L
#undef examples_Antenna_NORMAL
#define examples_Antenna_NORMAL 0L
#undef examples_Antenna_ICONIFIED
#define examples_Antenna_ICONIFIED 1L
#undef examples_Antenna_MAXIMIZED_HORIZ
#define examples_Antenna_MAXIMIZED_HORIZ 2L
#undef examples_Antenna_MAXIMIZED_VERT
#define examples_Antenna_MAXIMIZED_VERT 4L
#undef examples_Antenna_MAXIMIZED_BOTH
#define examples_Antenna_MAXIMIZED_BOTH 6L
#undef examples_Antenna_serialVersionUID
#define examples_Antenna_serialVersionUID 2673458971256075116LL
#undef examples_Antenna_EXIT_ON_CLOSE
#define examples_Antenna_EXIT_ON_CLOSE 3L
/*
 * Class:     examples_Antenna
 * Method:    login
 * Signature: (ILjava/lang/String;Ljava/lang/String;)C
 */
JNIEXPORT jchar JNICALL Java_examples_Antenna_login
  (JNIEnv *, jobject, jint, jstring, jstring);

/*
 * Class:     examples_Antenna
 * Method:    connectInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_examples_Antenna_connectInit
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
